(setq ibuffer-saved-filter-groups
      '(("home"
         ("Emacs-lisp" (or (filename . "\.el$")
                           (name . "\*scratch")))
         ("Clojure" (mode . clojure-mode))
         ("Ruby/Rails" (or (mode . ruby-mode)
                           (mode . haml-mode)
                           (mode . less-css-mode)))
         ("CSS" (or (mode . css-mode)
                    (mode . scss-mode)))
         ("HTML" (mode . html-mode))
         ("JS Templates" (mode . handlebars-mode))
         ("Go" (mode . go-mode))
         ("Terminals" (mode . term-mode))
         ("Scripts" (mode . sh-mode))
         ("Javascript / Coffee" (or (mode . js2-mode)
                                    (mode . js-mode)
                                    (mode . coffee-mode)))
         ("Docs" (or (mode . markdown-mode)
                     (mode . showoff-mode)))
         ("Code"  (filename . "code"))
         ("REPL" (or (mode . inferior-lisp-mode)
                     (mode . slime-repl-mode)))

         ("Shells" (or (mode . eshell-mode)))
         ("Magit" (name . "\*magit"))
         ("Org" (mode . org-mode))
         ("ERC" (mode . erc-mode))
         ("Dirs" (mode . dired-mode))
         ("Customize" (mode . Custom-mode))
         ("Help" (or (name . "\*Help\*")
                     (name . "\*Apropos\*")
                     (name . "\*info\*")))
         ("Scala" (mode . scala-mode))
         ("Man pages" (mode . Man-mode)))))

(add-hook 'ibuffer-mode-hook
          '(lambda ()
             (ibuffer-switch-to-saved-filter-groups "home")
             (ibuffer-auto-mode 1)))

(setq ibuffer-show-empty-filter-groups nil)
